### PR TITLE
People page

### PR DESCRIPTION
**Pull request by dstodolny**
Prismic changes to Badger Type to cater for the People Listing:

* Returned UID as the slug for the badger URL
* Merged Prismic fields first and last name into name - it’s better for populating the default slug value. Still return first and last name from the badger api
* Added order number to Prismic so that Badgers can be sorted (need the CEOs and Milo returned as first 4 badgers)
* Changed Skills from free text to group of text fields because they’re displayed in a list in the UI

**This must go in before https://github.com/redbadger/website-honestly/pull/333 can be merged because `make fetch` won't work with the old api**

### CODE REVIEW

**Comment by JoeStanton** [comment]
Looks good - it might be nice to add a test for someone with a Double-Barrelled name?

**Comment by asavin** [comment]
Yeah what @JoeStanton said - I was also thinking we're not getting any people with triple names are we? Like, more than 2 words long names with no dashes in between?

**Comment by JoeStanton** [comment]
http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/ 🙈

**Comment by grahammendick** [comment]
@JoeStanton @asavin Added tests to check for middle name and double barrelled first and last names

**Comment by asavin** [comment]
LGTM

**Pull request merged**
