### PR TITLE
add careerBrief attribute to the organisation

### PR DESCRIPTION
**Pull request by dstodolny**
### Pre-flight checklist

* allows badger brain to return `careerBrief` field for the requested organisation

- [ ] Unit tests
- [ ] GraphiQL tested
- [ ] Client app tested
- [ ] Gif added

### CODE REVIEW

**Comment by gregdorward** [comment]
Can this ticket be tested in isolation? I think we need to merge it in, in order to test https://github.com/redbadger/react.london/pull/339

**Comment by dstodolny** [comment]
Yes but you would have to test it locally.
1. Pull the project
2. Checkout to the `career-brief` branch
3. `npm start`
4. Open `localhost:3001/graphql`
5. See if you can access `careerBrief` information using this query
```
{
  allOrganisations {
    name
    careerBrief
  }
}
```

Ping me if you need any help with that.

**Comment by gregdorward** [comment]
Great, thanks for that, will give it a try

**Comment by gregdorward** [comment]
@dstodolny - I'm getting null values back for the careerBrief in but one case. Have we only set a value for "DevelopHer"?

`{
  "data": {
    "allOrganisations": [
      {
        "name": "Facebook",
        "careerBrief": null
      },
      {
        "name": "DevelopHer",
        "careerBrief": "Test"
      },
      {
        "name": "Trainline",
        "careerBrief": null
      },
      {
        "name": "Futurice",
        "careerBrief": null
      }
    ]
  }
}`

**Comment by dstodolny** [comment]
Yes I set the value only for `DevelopHer` when I was testing it.

**Comment by gregdorward** [comment]
Cool, I'm happy for this to be merged of you don't know of any reason why it might need to be held up?

**Comment by asavin** [comment]
Yeah let's merge this

**Comment by dstodolny** [comment]
Nope, it's good to go.

**Comment by gregdorward** [comment]
It doesn't look like I have write access, could you ping me an invite please @asavin?

**Pull request merged**
