### PR TITLE
Prismic Field-Specific Fetching

### PR DESCRIPTION
**Pull request by jameshopkins**
penguin
- Bit of a refactor of the Prismic fetching mechanism.
- Only query for Prismic fields that are specified in the GraphQL query selection set.

### Pre-flight checklist
- [x] Unit tests
- [ ] Unit tests for previewing, transforming data, etc
- [x] GraphiQL tested
- [x] Client app tested
- [x] Gif added

### CODE REVIEW

**Comment by jameshopkins** [comment]
The events listing and individual events works fine on the client app, but couldn't find a route for news yet? @sebflipper I know you were working on this on the `badger-brain` side. Have we not integrated it with `website-next` yet?

**Comment by sebflipper** [comment]
@jameshopkins yup, I'm currently working on the new News pages on the [`news` branch on `website-next`](https://github.com/redbadger/website-next/compare/news).

**Comment by jameshopkins** [comment]
Ok cool @sebflipper. Could maybe pair later if you fancy?

**Comment by asavin** [comment]
Closing this PR for now as it is very stale.

**Pull request closed without merging**
