### PR TITLE
Graphqlviz

### PR DESCRIPTION
**Pull request by asavin**
giphy 3

Documentation update

### CODE REVIEW

**Comment by AndrewBestbier** [comment]
+1 pretty cool

**Comment by lpil** [comment]
I don't think the image should be in the repo as there is no guarantee that it is accurate. S3 it from CI?

**Comment by asavin** [comment]
Can I install graphviz on CI?

**Comment by lpil** [comment]
I think Circle CI supports Ubuntu `apt` packages.

**Comment by asavin** [comment]
Ok I guess the plan would be to regenerate the diagram on each master push.

**Pull request closed without merging**
